### ISSUE TITLE
Where to include MongoDB / Mongoose connection code?

### ISSUE THREAD

**Issue by gswcm** [nuxt/express#115]
With the previous version of the template (the one where **nuxt** was used as an Express middleware) I managed to include **Mogoose connection code** in `server/index.js` so it was activated when Express server `listen()` method was invoked. 

With the new configuration relying on `serverMiddleware` I cannot think of a place to inject Mongoose initialization code because there is no explicit place related to connection setup. 

Also, where would I change default port number 3000 to something else if I need to? In the previous edition it was a pretty obvious place in `server/index.js` file.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/express-template/issues/c95">#c95</a>)</em></sub></div>

**Comment by gamelaster** [comment]
Initialize mongoose in `api/server.js`.
About the port, just follow the article in Nuxt FAQ:
https://nuxtjs.org/faq/host-port/

**Comment by jensgeffken** [comment]
hello there i see its already closed but i need help with nuxt ssr universal and serverMiddleware using mongoose models in api/server.js. I am trying already for quite a while but no success. 
I ll always get this error message:
`ERROR  ServerMiddleware Error: Cannot overwrite Message model once compiled.                                                     20:35:12  

  at new OverwriteModelError (node_modules\mongoose\lib\error\overwriteModel.js:20:11)
  at Mongoose.model (node_modules\mongoose\lib\index.js:522:13)
  at Object.<anonymous> (api\models\Message.js:38:27)`
What am i missing to make that work, using nuxt ssr universal and an express api server endpoint running at the same time ? Thanks

**Comment by shtse8** [comment]
> Initialize mongoose in `api/index.js`. About the port, just follow the article in Nuxt FAQ: https://nuxtjs.org/faq/host-port/

How can I initialize mongoose in `api/index.ts`? Could you give me an example? thanks.

**Comment by illyaBendik** [comment]
```
server/index.ts

import { Nitro } from "nitropack"
import mongoose from "mongoose"

export default async (_nitroApp: Nitro) => {
  const config = useRuntimeConfig();
  try {
    await mongoose.connect(config.MONGO_URI);
    console.log("Connected to MongoDB");
  } catch (e) {
    console.error(e);
  }
}
```
```
and then add this to nuxt.config.ts
nitro: {
    plugins: ["@/server/index.ts"]
}
```
