### ISSUE TITLE
How to Deploys to netlify?

### ISSUE THREAD

**Issue by thaycacac** [nuxt/express#135]
I try to deploy my website to netlify but not successful. It seems impossible to execute the command 
`npm run generate`

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/express-template/issues/c112">#c112</a>)</em></sub></div>

**Comment by nicoladl** [comment]
Have you read the documentation?
https://nuxtjs.org/faq/netlify-deployment/

What error is showed?

**Comment by josteph** [comment]
@nicoladl I was able to deploy this into netlify, but every request doesn't correspond with the API routes, returning 404 error not found.

Using Nuxt 2.2.0
