### ISSUE TITLE
pm2  cluster_mode issue

### ISSUE THREAD

**Issue by RezaHaidari** [nuxt/express#19]
Node 6.9.4
pm2 2.4.2
windows 10 64bit
16 gig ram

in fork mode works perfect

but when use cluster mode:

`pm2 start server.prod.js -i max --env production`

some instances stopped ! 

![pm2](https://cloud.githubusercontent.com/assets/12013210/24396252/c0541748-13b7-11e7-8954-fdce94c8850b.PNG)

**Comment by Atinux** [comment]
Can you share the logs @RezaHaidari ?
