### ISSUE TITLE
babel dependencies may be listed incorrectly causing deployment failures to Heroku

### ISSUE THREAD

**Issue by corsen2000** [nuxt/express#24]
In order to use Heroku's Nodejs build pack, I've created a `postinstall` script in `package.json` that runs `yarn build`.

This will failure though because the build relies on a few `babel` packages which are [currently listed as dev dependencies](https://github.com/nuxt/express/blob/master/template/package.json#L27).

Heroku does not install dev dependencies by default.

This should be able to be fixed locally either through Heroku configuration or by moving the dependencies locally outside of `dev`.

I'm filing this issue because it seems that it may be incorrect that these are listed as `devDependencies`. All other dependencies that are required for the build (including those from Nuxt) are listed as `dependencies` and work by default with the build packs decision to not install dev dependencies.

Should dev dependencies only be for packages that are used exclusively in development commands such as `nuxt dev`?

**Comment by Atinux** [comment]
Hi @corsen2000 

Sorry for the late answer, please take a look at https://nuxtjs.org/faq/heroku-deployment

You need to tell Heroku to install the dev dependencies in order to build the app.
