### ISSUE TITLE
Transpiling import/export routes on build

### ISSUE THREAD

**Issue by guumaster** [nuxt/express#25]
Is possible to use `import/export` features in the routes? I changed `server.js` to start like this: 

```
import Nuxt from 'nuxt'
import express from 'express'

import api from './api'
.... 
```
And `api/index.js` to this: 
```
import { Router } from 'express'
import users from './users'

const router = Router()

// Add USERS Routes
router.use(users)

export default router
```

It works during `npm run dev`, but not after `npm run build` and  `npm start`, I'm getting this error: 
``` 
function (exports, require, module, __filename, __dirname) { import Nuxt from 'nuxt';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
...
```

What should I change to enable this?

Thanks.

**Comment by Atinux** [comment]
Hi @guumaster 

I just changed the template to use [backpack](https://github.com/palmerhq/backpack) instead of babel, it should work now :)

**Comment by guumaster** [comment]
Thanks for that, seems easier to use it now. 

What's your opinion on making it even more simple to recognize which part is server side code only? Would you accept a PR with this structure: 

```
<root>
  |- server.js // => move to server/index.js

  |- server/  // =>  folder with express and server side code only
     |- api/
        |- users.js
        |- index.js
     |- index.js   // => main entry point for server only endpoints
    
```

**Comment by Atinux** [comment]
It makes sense, you can create a PR for that sure!
