### ISSUE TITLE
The build runs multiple times

### ISSUE THREAD

**Issue by phenrigomes** [nuxt/express#4]
Only:

npm install
npm run dev

![screenshot at 2017-02-13 11-01-34](https://cloud.githubusercontent.com/assets/596860/22886337/1fa4178c-f1dc-11e6-9fbc-3ccfd1ac8e8e.png)

**Comment by Atinux** [comment]
@phenrigomes we are aware about this, nothing to worry about it's from webpack when starting the server with the watch option (filesystem bug).
