### ISSUE TITLE
How do I change port to 80 on production???

### ISSUE THREAD

**Issue by andrisole92** [nuxt/express#42]
I have an error:
Error: connect ECONNREFUSED 127.0.0.1:3000
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

**Comment by fortil** [comment]
how was you to run it?

**Comment by andrisole92** [comment]
npm start

**Comment by fortil** [comment]
If you are in Ubuntu, use `sudo` before

**Comment by andrisole92** [comment]
I am on windows

**Comment by fortil** [comment]
Do you tried to change _package.json_ `"start": "cross-env NODE_ENV=production node server.js --port 80"` or in _nuxt.config.js_ file or in _https://nuxtjs.org/faq/host-port/_?

**Comment by andrisole92** [comment]
Thanks man.

**Comment by fortil** [comment]
your welcome
