### ISSUE TITLE
`npm run start` does not work in windows environment

### ISSUE THREAD

**Issue by corsen2000** [nuxt/express#6]
The command `NODE_ENV=production node server.js` will through an error in windows. I changed it to `set NODE_ENV=production&& node server.js` and things seem to work fine.

**Note: Not having a whitespace after the word production is required to make this work.**

I believe this command should also work under linux environments, but I can't test this.

Can we do something so that this works on windows by default?

**Comment by Atinux** [comment]
Hi @corsen2000 

I just updated the template to use [cross-env](https://www.npmjs.com/package/cross-env) for making it work on every platform, see my changes here: https://github.com/nuxt/express/commit/2c56245a41446e9e992a883a14cc487572e6c52c

Thank you for spotting this issue 👍

**Comment by corsen2000** [comment]
@Atinux thanks. I tested this locally and it works well.
