### ISSUE TITLE
Loop webpack building

### ISSUE THREAD

**Issue by tronjs** [nuxt/express#7]
Hi, I am not sure if this is a issue, but when I try to run `npm run dev`, there is seems like a bundle of loop webpack building instead of only one time building. (See the gif image below)
Why it takes too many building step? Please help, thank you guys!
```
Windows 10
# node -v
v7.3.0
# yarn version
yarn version v0.20.3
# npm -v
3.10.10
# vue -V
2.8.1
```
![event](https://cloud.githubusercontent.com/assets/25677842/23099655/c55ab296-f69e-11e6-9d1f-fd09c33a994b.gif)

**Comment by alexchopin** [comment]
#4
